@startuml

title test.seq
participant A
participant	C1 
participant C2
participant ArrayList
participant Object

alt if dead
    C1 --> C2 : void doStuff()
    alt if other
        C2 -> C1 : int test()
    else
        C2 -> C1 : C2 la()
        C2 -> C1 : C2 la2()
    end
end
C2 -> Object : ArrayList ALIST
C2 -> C1 : int test()
C2 -> C1: C2 la()
C2-> C1: int test()
C1 -> C1: C2 la()
C1 -> ArrayList : void countit()  
C1 ..> C2 : string la 
C1 ..> A : void start(int timeout)
@enduml
